# Generated by Django 3.2.5 on 2021-07-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transactionmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='msg',
            field=models.CharField(max_length=100),
        ),
    ]
